import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/ui/navbar/navbar";
import Provider from "@/lib/providers";

export const metadata: Metadata = {
  title: "Central Hackathon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-monument">
        <Provider>
          <Navbar />
          <div className="pt-20">{children}</div>
        </Provider>
      </body>
    </html>
  );
}
