import type { Metadata } from "next";
import "./globals.css";
import Provider from "@/lib/providers";

export const metadata: Metadata = {
  title: "Central Hackathon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-monument overflow-x-hidden">
        <Provider>
          <div>{children}</div>
          <div className="noise" />
        </Provider>
      </body>
    </html>
  );
}
